seed: 0
debug: false

mode: clip
exp_name: clip
checkpoint_dir: /home/harmanan/scratch/ckpt/${data.dataset}/${mode}_fold=${data.fold}_j${slurm_job_id}
save_weights: false
#checkpoint_dir: null #/h/harmanan/breast_us/.ckpt/${slurm_job_id}

pretrained: true
pretraining:
  data: breast
  style: clip
from_ckpt: null # /h/harmanan/breast_us/_checkpoint/biomedclip-${pretraining.data}/model_pureclip1.pth

wandb:
  name: ${exp_name}_fold=${data.fold}_slurmid=${slurm_job_id}
  project: MedCBM
  group: biomedclip
  tags: 
  log_images: false

slurm:
  qos: m2
  mem: 32G
  gpu: gpu:a40:1
  time: 8:00:00

data:
  dataset: CUB
  data_dir: /h/harmanan/breast_us/data/${data.dataset}
  fold: 0
  num_folds: 5
  splitting: holdout
  sampling: undersample
  sampling_ratio: 1.0
  crop_rois: true # whether to crop the images to the ROIs
  image_size: 224
  preprocessing: clip

  batch_size: 64
  augmentations:
    - translation
    - rotate
    - flip

  use_llm_output: false
  datasets: ["BrEaST", "BUSBRA"] # datasets to use, can be ["BrEaST", "BUSBRA", "ALL"]

training:
  num_epochs: 300
  lr_scheduler: cosine
  pretrained: false
  from_ckpt: /checkpoint/harmanan/16902799/model_epoch299_auc0.55.ckpt
  accumulate_grad_steps: 1

optimizer:
  name: adamw
  lr: 1e-05
  wd: 0 # weight decay
  frozen_epochs: 0
  warmup_epochs: 30

cbm:
  num_concepts: 112
  num_birads: 6 # 0, 1, 2, 3, 4, 5
  num_classes: 200
  concepts: [1, 4, 6, 7, 10, 14, 15, 20, 21, 23, 25, 29, 30, 35, 36, 38,
    40, 44, 45, 50, 51, 53, 54, 56, 57, 59, 63, 64, 69, 70, 72,
    75, 80, 84, 90, 91, 93, 99, 101, 106, 110, 111, 116, 117, 119,
    125, 126, 131, 132, 134, 145, 149, 151, 152, 153, 157, 158, 163,
    164, 168, 172, 178, 179, 181, 183, 187, 188, 193, 194, 196, 198,
    202, 203, 208, 209, 211, 212, 213, 218, 220, 221, 225, 235, 236,
    238, 239, 240, 242, 243, 244, 249, 253, 254, 259, 260, 262, 268,
    274, 277, 283, 289, 292, 293, 294, 298, 299, 304, 305, 308, 309,
    310, 311]
  architecture: multitask # bottleneck, multitask, fusion
  concept_weights: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

loss:
  det_loss: ce
  concept_loss: ce
  birads_loss: ce

clip:
  d: 512
  embedding_dim: 512
  adapter_dim: 512
  clip_weight: 0.0
  det_weight: 1.0
  concept_weight: 0.0
  birads_weight: 0.0
  use_llm_output: false
  backbone: vit

metrics:
  tune_threshold: true

device: cuda
use_amp: false