seed: 0
debug: false

mode: llama
exp_name: ${backbone}-bus
checkpoint_dir: /home/harmanan/scratch/ckpt/${data.dataset}/${mode}_fold=${data.fold}_j${slurm_job_id}
save_weights: false

pretrained: false
pretraining:
  data: breast
  style: supervised

from_ckpt: /h/harmanan/breast_us/_checkpoint/${backbone}-${pretraining.data}-${pretraining.style}/fold${data.fold}.pth

wandb:
  name: ${exp_name}_fold=${data.fold}_slurmid=${slurm_job_id}
  project: MedCBM
  group: llama
  tags: 
  log_images: true

slurm:
  qos: long
  mem: 48G
  gpu: gpu:a40:1
  time: 48:00:00

data:
  dataset: BREAST_US
  data_dir: /h/harmanan/breast_us/data/${data.dataset}
  fold: 0
  num_folds: 5
  splitting: kfold
  sampling: undersample
  sampling_ratio: 1.0
  crop_rois: true
  use_llm_output: false
  image_size: 256

  batch_size: 1
  augmentations:
    - translation

  datasets: ["BrEaST", "BUSBRA"] # datasets to use, can be ["BrEaST", "BUSBRA", "ALL"]

training:
  num_epochs: 1
  lr_scheduler: cosine
  pretrained: true
  from_ckpt: null
  accumulate_grad_steps: 1

optimizer:
  name: adamw
  encoder_lr: 1e-05
  main_lr: 1e-05
  wd: 1e-4 # weight decay
  encoder_frozen_epochs: 0
  encoder_warmup_epochs: 0
  main_frozen_epochs: 0
  main_warmup_epochs: 0

backbone: medgemma
num_classes: 2

lvlm:
  prompt_mode: reasoning
  include_mask: false
  include_bbox: false

cbm: # delete later!!
  num_concepts: 15
  num_classes: 2
  concepts: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

learning_rate: 0.001
loss: cross_entropy

device: cuda
use_amp: false

peft:
  enabled: true
  method: lora
  output_dir: /home/harmanan/projects/aip-medilab/harmanan/breast_us/peft_ckpts
  prompt_mode: guidelines
  lora_r: 16
  lora_alpha: 32
  lora_dropout: 0.05
  target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
  lr: 1e-4
  weight_decay: 0.0
  grad_accum_steps: 1
  max_grad_norm: 1.0
  log_steps: 25

# python3 run.py -y llama -o wandb.group=LLaMA_LaBo_1 data.fold=0