DDSM_CONCEPT_BANK = [
    "Regular shape",
    "Irregular shape",
    "Lobulated shape",
    "Circumscribed margins",
    "Ill-defined margins",
    "Spiculated margins",
    "Obscured margins",
    "Microlobulated margins",
    "Pleomorphic calcification",
    "Amorphous calcification",
    "Fine linear calcification",
    "Branching calcification",
    "Vascular calcification",
    "Coarse calcification",
    "Punctate calcification",
    "Lucent calcification",
    "Eggshell calcification",
    "Round calcification",
    "Regular calcification",
    "Dystrophic calcification",
    "Clustered calcification distribution",
    "Segmental calcification distribution",
    "Linear calcification distribution",
    "Scattered calcification distribution",
    "Regional calcification distribution",
    "Low breast density",
    "Moderate breast density",
    "High breast density",
    "Architectural distortion",
    "Asymmetry",
] # len = 30